/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package edu.rit.poe.atomix;

public final class R {
    public static final class attr {
    }
    public static final class drawable {
        public static final int atomix_icon=0x7f020000;
        public static final int atomix_logo=0x7f020001;
        public static final int droid_atomix=0x7f020002;
        public static final int droid_atomix1=0x7f020003;
        public static final int droid_atomix3=0x7f020004;
        public static final int logo=0x7f020005;
    }
    public static final class id {
        public static final int atomix_title=0x7f050010;
        public static final int bglayout=0x7f05000f;
        public static final int continue_button=0x7f050012;
        public static final int continue_dialog=0x7f050000;
        public static final int detailstable=0x7f050003;
        public static final int goal_details_solution=0x7f05000a;
        public static final int goal_dialog=0x7f050006;
        public static final int goal_dialog2=0x7f050007;
        public static final int goal_dialog_atomix_image=0x7f050008;
        public static final int goal_dialog_level=0x7f050009;
        public static final int help_button=0x7f050014;
        public static final int icon=0x7f05000e;
        public static final int level_completed=0x7f05000c;
        public static final int level_name=0x7f05000d;
        public static final int level_number=0x7f05000b;
        public static final int main_button_list=0x7f050011;
        public static final int new_game_button=0x7f050013;
        public static final int new_name=0x7f050004;
        public static final int newgame_dialog=0x7f050002;
        public static final int play_button=0x7f050005;
        public static final int quit_button=0x7f050015;
        public static final int saved_games_list=0x7f050001;
    }
    public static final class layout {
        public static final int continue_dialog=0x7f030000;
        public static final int game_dialog=0x7f030001;
        public static final int goal_dialog=0x7f030002;
        public static final int level_row=0x7f030003;
        public static final int main=0x7f030004;
        public static final int menu=0x7f030005;
    }
    public static final class string {
        public static final int app_name=0x7f040000;
        public static final int home_title=0x7f040001;
    }
}
