/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package edu.rit.poe.atomix;

public final class R {
    public static final class attr {
    }
    public static final class drawable {
        public static final int arrow_left=0x7f020000;
        public static final int arrow_right=0x7f020001;
        public static final int atomix_icon=0x7f020002;
        public static final int atomix_logo=0x7f020003;
        public static final int droid_atomix=0x7f020004;
        public static final int droid_atomix1=0x7f020005;
        public static final int droid_atomix3=0x7f020006;
        public static final int levels_cclicense=0x7f020007;
        public static final int logo=0x7f020008;
        public static final int menu_icons_license=0x7f020009;
        public static final int options=0x7f02000a;
        public static final int undo=0x7f02000b;
        public static final int wall_bottom_left=0x7f02000c;
        public static final int wall_bottom_right=0x7f02000d;
        public static final int wall_horizontal=0x7f02000e;
        public static final int wall_horizontal_bottomx=0x7f02000f;
        public static final int wall_horizontal_left_end=0x7f020010;
        public static final int wall_horizontal_right_end=0x7f020011;
        public static final int wall_horizontal_topx=0x7f020012;
        public static final int wall_single=0x7f020013;
        public static final int wall_top_left=0x7f020014;
        public static final int wall_top_right=0x7f020015;
        public static final int wall_vertical=0x7f020016;
        public static final int wall_vertical_bottom_end=0x7f020017;
        public static final int wall_vertical_leftx=0x7f020018;
        public static final int wall_vertical_rightx=0x7f020019;
        public static final int wall_vertical_top_end=0x7f02001a;
    }
    public static final class id {
        public static final int atomix_title=0x7f05000c;
        public static final int bglayout=0x7f05000b;
        public static final int continue_button=0x7f05000e;
        public static final int continue_dialog=0x7f050000;
        public static final int detailstable=0x7f050003;
        public static final int goal_dialog=0x7f050006;
        public static final int help_button=0x7f050010;
        public static final int level_completed_moves=0x7f05000a;
        public static final int level_completed_seconds=0x7f050008;
        public static final int level_name=0x7f050009;
        public static final int level_number=0x7f050007;
        public static final int main_button_list=0x7f05000d;
        public static final int new_game_button=0x7f05000f;
        public static final int new_name=0x7f050004;
        public static final int newgame_dialog=0x7f050002;
        public static final int play_button=0x7f050005;
        public static final int quit_button=0x7f050011;
        public static final int saved_games_list=0x7f050001;
    }
    public static final class layout {
        public static final int continue_dialog=0x7f030000;
        public static final int game_dialog=0x7f030001;
        public static final int goal_dialog=0x7f030002;
        public static final int level_row=0x7f030003;
        public static final int menu=0x7f030004;
    }
    public static final class string {
        public static final int app_name=0x7f040000;
        public static final int completed_moves_text=0x7f040008;
        /**  Strings for the Levels List 
         */
        public static final int completed_seconds_text=0x7f040007;
        public static final int confirm_no=0x7f04001c;
        /**  General dialog string literals 
         */
        public static final int confirm_yes=0x7f04001b;
        public static final int goal_dialog_return_button=0x7f04001a;
        /**  String literals for the zoomed goal viewer 
         */
        public static final int goal_dialog_title=0x7f040019;
        /**  Activity Titles 
         */
        public static final int home_title=0x7f040001;
        public static final int levels_title=0x7f040002;
        /**  String literals for the Main Menu 
         */
        public static final int main_menu_continue=0x7f040003;
        public static final int main_menu_help=0x7f040005;
        public static final int main_menu_new_game=0x7f040004;
        public static final int main_menu_quit=0x7f040006;
        /**  String literals for the options menu 
         */
        public static final int menu_goal=0x7f04000d;
        public static final int menu_levels=0x7f04000e;
        public static final int menu_main=0x7f040013;
        public static final int menu_next=0x7f040010;
        public static final int menu_previous=0x7f040011;
        public static final int menu_quit=0x7f040014;
        public static final int menu_restart=0x7f040012;
        public static final int menu_undo=0x7f04000f;
        public static final int overwrite_dialog_text=0x7f040016;
        /**  String literals for the Overwrite Confirmation Menu 
         */
        public static final int overwrite_dialog_title=0x7f040015;
        public static final int unsaved_dialog_text=0x7f040018;
        /**  Strings for the abandon unsaved level 
         */
        public static final int unsaved_dialog_title=0x7f040017;
        public static final int win_dialog_levels_button=0x7f04000c;
        public static final int win_dialog_next_button=0x7f04000b;
        public static final int win_dialog_text=0x7f04000a;
        /**  Strings for the Win Level Dialog 
         */
        public static final int win_dialog_title=0x7f040009;
    }
}
